import React from 'react';
import { useEffect, useState } from 'react'; import { Fingerprint } from 'lucide-react';
import Header from '../components/Header'; import UploadPanel from '../components/UploadPanel'; import LiveFeed from '../components/LiveFeed'; import ReportCard from '../components/ReportCard'; import ProcessingLoader from '../components/ProcessingLoader';
const API=import.meta.env.VITE_BACKEND_URL||'http://localhost:8000';
const phrases=['Establishing a trusted assessment channel…','Mapping the API attack surface…','Correlating certificate trust signals…','Running AI-guided exploit analysis…','Validating high-risk security controls…','Sealing the final security report…'];
const isSuccess=status=>['success','successful','completed','complete','done'].includes(String(status||'').toLowerCase());
const isFailure=status=>['failure','failed','error','cancelled','canceled'].includes(String(status||'').toLowerCase());
export default function Assess(){const [cert,setCert]=useState(null),[doc,setDoc]=useState(null),[target,setTarget]=useState(''),[scan,setScan]=useState(null),[events,setEvents]=useState([]),[report,setReport]=useState(null),[lookup,setLookup]=useState(''),[error,setError]=useState(''),[phrase,setPhrase]=useState(phrases[0]);
useEffect(()=>{if(scan?.status!=='running')return;let step=0;const timer=setInterval(()=>{step=(step+1)%phrases.length;setPhrase(phrases[step])},2200);return()=>clearInterval(timer)},[scan?.status]);
useEffect(()=>{if(!scan?.jobId||scan.status!=='running')return;let stopped=false;const poll=async()=>{try{const response=await fetch(`${API}/job/${encodeURIComponent(scan.jobId)}`);const payload=await response.json();if(!response.ok)throw Error(payload.detail||'Unable to retrieve assessment status.');const status=payload.status||payload.state||payload.job_status||'running';setEvents(current=>[...current.slice(-4),{message:payload.message||payload.detail||`Assessment status: ${status}`,detail:'CID orchestration engine is processing your authorized test.',progress:payload.progress??payload.percent_complete??'—'}]);if(isSuccess(status)){const final=await fetch(`${API}/jobs/${encodeURIComponent(scan.jobId)}/final`);if(!final.ok)throw Error('Assessment completed, but the final PDF could not be retrieved.');const blob=await final.blob();if(stopped)return;const url=URL.createObjectURL(blob);setReport({test_id:scan.jobId,created_at:new Date().toLocaleString(),risk_score:payload.risk_score||payload.score||'—',downloadUrl:url});setScan(current=>({...current,status:'complete'}));return}if(isFailure(status)){setScan(current=>({...current,status:'failed'}));setError(payload.message||'The security assessment failed. Please review the inputs and try again.');return}}catch(err){if(!stopped){setScan(current=>({...current,status:'failed'}));setError(err.message)}}};poll();const timer=setInterval(poll,1500);return()=>{stopped=true;clearInterval(timer)}},[scan?.jobId,scan?.status]);
const launch=async()=>{if(!cert||!doc||!target.trim())return setError('Add the API URL and both required files to initialize the security assessment.');try{new URL(target)}catch{return setError('Enter a valid API URL, including http:// or https://.')}setError('');setReport(null);setEvents([]);try{const data=new FormData();data.append('certificate',cert);data.append('swagger_doc',doc);data.append('url',target.trim());const response=await fetch(`${API}/jobs`,{method:'POST',body:data});const payload=await response.json();if(!response.ok)throw Error(payload.detail||payload.message||'Could not start this assessment.');const jobId=payload.job_id||payload.id;if(!jobId)throw Error('The assessment service did not return a job ID.');setScan({jobId,test_id:jobId,status:'running'});setPhrase(phrases[0])}catch(err){setError(err.message)}};
const lookupReport=async e=>{e.preventDefault();setError('Report lookup is managed from the Reports page.');};return <><Header title={<>Sentinel <em>for APIs</em></>}/><div className="assess-grid"><section><div className="hero"><div><p className="tag">CID INTELLIGENCE ENGINE</p><h2>See the attack surface <em>before</em> they do.</h2><p>Upload your API contract and certificate. CID maps risk, validates exposure, and turns signals into an executive-ready report.</p></div><div className="fingerprint"><Fingerprint size={78}/></div></div><UploadPanel {...{cert,setCert,doc,setDoc,target,setTarget,onLaunch:launch,loading:scan?.status==='running',error}}/>{scan?.status==='running'&&<ProcessingLoader jobId={scan.jobId} phrase={phrase}/>}<LiveFeed scan={scan} events={events}/></section><aside className="side-content"><ReportCard {...{report,lookup,setLookup,onLookup:lookupReport}}/><div className="posture"><span>SECURITY POSTURE</span><h2>Continuously<br/><em>aware.</em></h2><b>82<small>/100</small></b><p>AI signal coverage across authentication, inputs and infrastructure.</p></div></aside></div></>}
