import React from 'react';
import { useEffect, useState } from 'react';
import { Fingerprint } from 'lucide-react';
import Header from '../components/Header'; import UploadPanel from '../components/UploadPanel'; import LiveFeed from '../components/LiveFeed'; import ReportCard from '../components/ReportCard'; import ProcessingLoader from '../components/ProcessingLoader';

const API = (import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000').replace(/\/+$/, '');
const phrases = ['Establishing a trusted assessment channel…', 'Mapping the API attack surface…', 'Correlating certificate trust signals…', 'Running AI-guided exploit analysis…', 'Validating high-risk security controls…', 'Sealing the final security report…'];
const isSuccess = status => ['success', 'successful', 'completed', 'complete', 'done'].includes(String(status || '').toLowerCase());
const isFailure = status => ['failure', 'failed', 'error', 'cancelled', 'canceled'].includes(String(status || '').toLowerCase());

export default function Assess() {
  const [cert, setCert] = useState(null), [target, setTarget] = useState(''), [scan, setScan] = useState(null), [events, setEvents] = useState([]), [report, setReport] = useState(null), [lookup, setLookup] = useState(''), [error, setError] = useState(''), [phrase, setPhrase] = useState(phrases[0]);
  useEffect(() => { if (scan?.status !== 'running') return; let index = 0; const timer = setInterval(() => { index = (index + 1) % phrases.length; setPhrase(phrases[index]); }, 2200); return () => clearInterval(timer); }, [scan?.status]);
  useEffect(() => { if (!scan?.jobId || scan.status !== 'running') return; let stopped = false; const poll = async () => { try { const response = await fetch(`${API}/jobs/${encodeURIComponent(scan.jobId)}`); const payload = await response.json(); if (!response.ok) throw Error(payload.message || 'Unable to retrieve assessment status.'); const status = payload.status || 'RUNNING'; setEvents(current => [...current.slice(-4), { message: `Assessment status: ${status}`, detail: payload.updated_at ? `Last updated ${payload.updated_at}` : 'CID orchestration engine is processing your authorized test.', progress: '—' }]); if (isSuccess(status)) { const final = await fetch(`${API}/jobs/${encodeURIComponent(scan.jobId)}/final`); const finalPayload = await final.json(); if (!final.ok) throw Error(finalPayload.message || 'Assessment completed, but the final report could not be retrieved.'); if (stopped) return; setReport({ test_id: scan.jobId, created_at: new Date().toLocaleString(), report: finalPayload.report }); setScan(current => ({ ...current, status: 'complete' })); return; } if (isFailure(status)) { setScan(current => ({ ...current, status: 'failed' })); setError(payload.error || 'The security assessment failed. Please review the inputs and try again.'); } } catch (err) { if (!stopped) { setScan(current => ({ ...current, status: 'failed' })); setError(err.message); } } }; poll(); const timer = setInterval(poll, 1500); return () => { stopped = true; clearInterval(timer); }; }, [scan?.jobId, scan?.status]);
  const launch = async () => { if (!target.trim()) return setError('Add a Swagger or OpenAPI URL to begin the security assessment.'); try { new URL(target); } catch { return setError('Enter a valid Swagger/OpenAPI URL, including http:// or https://.'); } setError(''); setReport(null); setEvents([]); try { const certs = cert ? { client_cert_pem: await cert.text() } : undefined; const response = await fetch(`${API}/jobs`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ swagger_url: target.trim(), ...(certs && { certs }) }) }); const payload = await response.json(); if (!response.ok) throw Error(payload.message || 'Could not start this assessment.'); if (!payload.job_id) throw Error('The assessment service did not return a job ID.'); setScan({ jobId: payload.job_id, test_id: payload.job_id, status: 'running' }); setPhrase(phrases[0]); } catch (err) { setError(err.message); } };
  const lookupReport = event => { event.preventDefault(); setError('Enter a Swagger URL and run a new assessment. Job history is not exposed by this backend contract.'); };
  return <><Header title={<>Sentinel <em>for APIs</em></>}/><div className="assess-grid"><section><div className="hero"><div><p className="tag">CID INTELLIGENCE ENGINE</p><h2>See the attack surface <em>before</em> they do.</h2><p>Provide an OpenAPI URL and optional client certificate. CID maps risk, validates exposure, and turns signals into an executive-ready report.</p></div><div className="fingerprint"><Fingerprint size={78}/></div></div><UploadPanel {...{ cert, setCert, target, setTarget, onLaunch: launch, loading: scan?.status === 'running', error }}/>{scan?.status === 'running' && <ProcessingLoader jobId={scan.jobId} phrase={phrase}/>}<LiveFeed scan={scan} events={events}/></section><aside className="side-content"><ReportCard {...{ report, lookup, setLookup, onLookup: lookupReport }}/><div className="posture"><span>SECURITY POSTURE</span><h2>Continuously<br/><em>aware.</em></h2><b>82<small>/100</small></b><p>AI signal coverage across authentication, inputs and infrastructure.</p></div></aside></div></>;
}
